### ISSUE TITLE
 feat: ignite-metrics - Add telemetry without UI

### ISSUE THREAD

**Issue by SgtPooki** [laurentsenta/pl-diagnose#10]
Add telemetry according to https://github.com/ipfs/ipfs-gui/issues/105.

See https://github.com/ipfs/ipfs-gui/issues/105#issuecomment-1386291301 for more
details about why there is no UI treatment.

Users will be able to opt out by executing the function `removeMetricsConsent` in their browser console: `removeMetricsConsent()`. They can re-add consent using `addMetricsConsent()`.

**Comment by SgtPooki** [comment]
I can't assign this to myself (ping @laurentsenta ) but here's FYI that I'm tackling this one

**Comment by laurentsenta** [comment]
@SgtPooki, I've added you as a maintainer, let me know if you think we should transfer this repo to ipfs or another org.

**Comment by SgtPooki** [comment]
@laurentsenta we should probably move this one to ipfs-shipyard
